# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/actions/upload-artifact#where-does-the-upload-go
name: pwshPlaces-Windows-Build
on:
  push:
    paths-ignore:
      - '**.md'
      - 'media/**'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'media/**'
      - 'LICENSE'
jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Display the path
      shell: powershell
      run: echo ${env:PATH}
    - name: Version Display
      shell: powershell
      run: $PSVersionTable
    - name: NuGet Latest
      shell: powershell
      run: Install-PackageProvider -Name "NuGet" -Confirm:$false -Force -Verbose
    - name: PowerShellGet Latest
      shell: powershell
      run: Install-Module -Name PowerShellGet -Repository PSGallery -Force
    - name: Bootstrap
      shell: powershell
      run: ./actions_bootstrap.ps1
    - name: Retrieve Google API Key
      env:
        GoogleAPIKey: ${{ secrets.GoogleAPIKey }}
    - name: Test and Build
      shell: powershell
      run: Invoke-Build -File .\src\pwshPlaces.build.ps1
    - name: Upload pester results
      uses: actions/upload-artifact@v2
      with:
        name: pester-results
        path: .\src\Artifacts\testOutput
        if-no-files-found: warn
    - name: Upload zip module archive build
      uses: actions/upload-artifact@v2
      with:
        name: zip-archive
        path: .\src\Archive
        if-no-files-found: warn
